#!/usr/bin/env python3
"""Regenerate supabase/functions/render-document/fonts.ts.

The QR-bill renderer must embed a font: pdf-lib's Standard-14 Helvetica is
WinAnsi-encoded and throws on the Latin Extended A characters SIX permits in
names, so the render would work until a customer was called Wiśniewski.

The font is inlined as base64 rather than bundled as a binary asset because the
Supabase management API accepts text files only. Bundling the TTFs would tie
every deploy of this function to the CLI.

Requires fonttools:  pip install fonttools
Run:                 python3 scripts/build-fonts.py
"""

from __future__ import annotations

import base64
import subprocess
import sys
import textwrap
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FONT_DIR = ROOT / "supabase" / "functions" / "render-document" / "fonts"
OUT = ROOT / "supabase" / "functions" / "render-document" / "fonts.ts"

# SIX Implementation Guidelines v2.3, 4.1.1: Latin-1 Supplement, Latin
# Extended A, the Romanian comma-below letters, and the euro sign.
RANGES = "U+0020-007E,U+00A0-00FF,U+0100-017F,U+0218-021B,U+20AC"

# The same repertoire, expanded, for the coverage check below.
CODEPOINTS = (
    list(range(0x0020, 0x007F))
    + list(range(0x00A0, 0x0100))
    + list(range(0x0100, 0x0180))
    + list(range(0x0218, 0x021C))
    + [0x20AC]
)

HEADER = """// Liberation Sans, subsetted to the character repertoire SIX permits and
// inlined as base64.
//
// This is not an optimisation — it is what makes the function deployable
// through the management API, which accepts text files only. Bundling the
// binary TTFs would tie every deploy to the CLI.
//
// Subsetted to U+0020-007E, U+00A0-00FF, U+0100-017F, U+0218-021B and U+20AC
// (SIX Implementation Guidelines v2.3, 4.1.1). The generator verifies that not
// one of those 324 codepoints was dropped — a missing glyph would surface as a
// customer name that will not render, which is exactly the failure this font
// exists to prevent.
//
// Licence: SIL Open Font License 1.1. The full text ships in fonts/LICENSE
// alongside the unmodified originals, which stay in the repo as the source of
// truth for regenerating this file.
//
// Generated by scripts/build-fonts.py — do not hand-edit.
"""

FOOTER = """
function decode(b64: string): Uint8Array {
  const bin = atob(b64);
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  return bytes;
}

export const liberationSansRegular = () => decode(LIBERATION_SANS_REGULAR_B64);
export const liberationSansBold = () => decode(LIBERATION_SANS_BOLD_B64);
"""


def subset(weight: str) -> Path:
    src = FONT_DIR / f"LiberationSans-{weight}.ttf"
    dst = FONT_DIR / f"subset-{weight}.ttf"
    if not src.exists():
        sys.exit(f"missing {src} — see fonts/LICENSE for the upstream source")
    subprocess.run(
        [
            "pyftsubset", str(src),
            f"--unicodes={RANGES}",
            "--layout-features=",
            "--no-hinting",
            "--desubroutinize",
            "--drop-tables+=GSUB,GPOS,GDEF,DSIG",
            f"--output-file={dst}",
        ],
        check=True,
        capture_output=True,
    )
    return dst


def assert_full_coverage(path: Path, weight: str) -> None:
    """A subset that silently dropped a glyph is worse than no subset at all."""
    from fontTools.ttLib import TTFont

    font = TTFont(path)
    covered = set()
    for table in font["cmap"].tables:
        covered.update(table.cmap.keys())
    missing = [c for c in CODEPOINTS if c not in covered]
    if missing:
        sample = " ".join(f"U+{c:04X}" for c in missing[:10])
        sys.exit(f"{weight}: subset dropped {len(missing)} codepoints, e.g. {sample}")


def main() -> None:
    parts = [HEADER]
    for weight, var in (("Regular", "LIBERATION_SANS_REGULAR"),
                        ("Bold", "LIBERATION_SANS_BOLD")):
        path = subset(weight)
        assert_full_coverage(path, weight)
        b64 = base64.b64encode(path.read_bytes()).decode()
        wrapped = "\n".join(textwrap.wrap(b64, 100))
        parts.append(f'\nconst {var}_B64 = `\n{wrapped}\n`.replace(/\\s/g, "");\n')
        print(f"{weight}: {path.stat().st_size:,} bytes -> {len(b64):,} base64 chars")

    parts.append(FOOTER)
    OUT.write_text("\n".join(parts))
    print(f"wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
